language: node_js

node_js:
  - "lts/*"

install:
  - travis_retry npm install

script:
  - npm run lint
  - npm run build
  - npm run test:ci
after_success:
  - npm run semantic-release

notifications:
  email:
    on_success: never
    on_failure: always
