language: node_js

node_js:
  - "lts/*"

install:
  - travis_retry npm install

before_script:
  - npm run lint
script:
  - npm run build
  - npm run coveralls
after_success:
  - npm run semantic-release

notifications:
  email:
    on_success: never
    on_failure: always
